/// Flutter icons Branch
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Branch
///      fonts:
///       - asset: fonts/Branch.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Branch {
  Branch._();

  static const _kFontFam = 'Branch';
  static const String _kFontPkg = null;

  static const IconData admin_corner = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrange_meeting = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mid_admin_list = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_branch = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
